# -*- coding: utf-8 -*-
"""Cards_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pcZo1GzrhY4RKtMh9RHSd4XjB-PVp_FE
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d "gpiosenka/cards-image-datasetclassification"

!unzip /content/cards-image-datasetclassification.zip

from tensorflow.keras.applications import EfficientNetB2
base_layer = EfficientNetB2(include_top=False, input_shape=(224,224,3), weights='imagenet')

base_layer.summary()

for layer in base_layer.layers[::4]:
  layer.trainable = True

from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Sequential
model = Sequential([base_layer,
                    Flatten(),
                    Dense(700, activation='relu'),
                    Dense(1400, activation='relu'),
                    Dense(53, activation='softmax')
                  ])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

from tensorflow.keras.preprocessing.image import ImageDataGenerator
generator = ImageDataGenerator(rescale=1./255)
train_data = generator.flow_from_directory('/content/train', target_size=(224,224), batch_size=32, class_mode='sparse')

test_data = generator.flow_from_directory('/content/test', target_size=(224,224), batch_size=32, class_mode='sparse')

val_data = generator.flow_from_directory('/content/valid', target_size=(224,224), batch_size=32, class_mode='sparse')

model.fit(train_data, epochs=8, validation_data=val_data)

import cv2
import numpy as np

def predict(path):
  img_arr = cv2.imread(path)
  img_res = cv2.resize(img_arr, (224,224))
  img_reshape = img_res.reshape((1,224,224,3))/255
  res = model.predict(img_reshape)
  res = np.argmax(res)
  return class_labels[res]

train_data.class_indices

a = train_data.class_indices
class_labels = dict(zip(a.values(), a.keys()))
class_labels

model.evaluate(test_data)

predict('/content/depositphotos_22389075-stock-illustrationjpg.jpg')

model.save('Cards_classifier_model.keras')